### ISSUE TITLE
ロケールテキストを日本語化

### ISSUE THREAD

**Issue by fixeders** [fixeders/4696#17]
Gem: 'rails -i18n'

**Comment by fixeders** [comment]
*config/application.rb*
```ruby
config.i18n.default_locale = :ja
```

**Comment by fixeders** [comment]
*ja.yml*
```yml
ja:
  activerecord:
    attributes:
      カラム名: 値
      ...略
```
